version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/TriviaAPI
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.m2
            - ~/TriviaAPI
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/TriviaAPI
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: gradle test
#      - store_test_results:
#          path: reports/junit
#      - store_artifacts:
#          path: reports/junit
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/TriviaAPI
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: build
          command: gradle build -x test
workflows:
  version: 2
  test_lint:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
